version: '3.8'

services:
  frontend:
    build:
      context: .  # Indica la ruta del proyecto frontend (en este caso la raíz del proyecto)
      dockerfile: docker/Dockerfile  # Especifica la ruta del Dockerfile dentro de la carpeta docker
      #name: nexus1-frontend-build
    image: nexus1-frontend:latest
    container_name: nexus1-frontend
    ports:
      - "5173:5173"  # Exponer el puerto Vite
    volumes:
      - .:/app  # Monta el directorio raíz de tu proyecto en /usr/src/app dentro del contenedor
      - /app/node_modules
    networks:
      - test  # La red común para frontend y backend
networks:
  test:
    name: nexus1-backend-project
